"""init

Revision ID: 5c90ab9cd617
Revises: 
Create Date: 2025-09-24 15:52:38.601409

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5c90ab9cd617'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('keys',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('key_hash', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('role', sa.Enum('USER', 'WORKER', 'ADMIN', name='keyrole'), nullable=False),
    sa.Column('created_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_used', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_keys_active'), 'keys', ['active'], unique=False)
    op.create_index(op.f('ix_keys_created_date'), 'keys', ['created_date'], unique=False)
    op.create_index(op.f('ix_keys_key_hash'), 'keys', ['key_hash'], unique=True)
    op.create_index(op.f('ix_keys_label'), 'keys', ['label'], unique=True)
    op.create_index(op.f('ix_keys_last_used'), 'keys', ['last_used'], unique=False)
    op.create_index(op.f('ix_keys_role'), 'keys', ['role'], unique=False)
    op.create_table('jobs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('owner_key_id', sa.Uuid(), nullable=False),
    sa.Column('worker_key_id', sa.Uuid(), nullable=True),
    sa.Column('definition', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('alto_required', sa.Boolean(), nullable=False),
    sa.Column('proarc_json_required', sa.Boolean(), nullable=False),
    sa.Column('state', sa.Enum('NEW', 'QUEUED', 'PROCESSING', 'ERROR', 'DONE', 'CANCELLED', name='processingstate'), nullable=False),
    sa.Column('proarc_json_uploaded', sa.Boolean(), nullable=False),
    sa.Column('created_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_change', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('log', sa.String(), nullable=True),
    sa.Column('log_user', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['owner_key_id'], ['keys.id'], ),
    sa.ForeignKeyConstraint(['worker_key_id'], ['keys.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_alto_required'), 'jobs', ['alto_required'], unique=False)
    op.create_index(op.f('ix_jobs_created_date'), 'jobs', ['created_date'], unique=False)
    op.create_index(op.f('ix_jobs_finished_date'), 'jobs', ['finished_date'], unique=False)
    op.create_index(op.f('ix_jobs_last_change'), 'jobs', ['last_change'], unique=False)
    op.create_index(op.f('ix_jobs_owner_key_id'), 'jobs', ['owner_key_id'], unique=False)
    op.create_index(op.f('ix_jobs_proarc_json_required'), 'jobs', ['proarc_json_required'], unique=False)
    op.create_index(op.f('ix_jobs_proarc_json_uploaded'), 'jobs', ['proarc_json_uploaded'], unique=False)
    op.create_index(op.f('ix_jobs_started_date'), 'jobs', ['started_date'], unique=False)
    op.create_index(op.f('ix_jobs_state'), 'jobs', ['state'], unique=False)
    op.create_index(op.f('ix_jobs_worker_key_id'), 'jobs', ['worker_key_id'], unique=False)
    op.create_table('images',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('imagehash', sa.String(), nullable=True),
    sa.Column('image_uploaded', sa.Boolean(), nullable=False),
    sa.Column('alto_uploaded', sa.Boolean(), nullable=False),
    sa.Column('created_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_images_alto_uploaded'), 'images', ['alto_uploaded'], unique=False)
    op.create_index(op.f('ix_images_created_date'), 'images', ['created_date'], unique=False)
    op.create_index(op.f('ix_images_image_uploaded'), 'images', ['image_uploaded'], unique=False)
    op.create_index(op.f('ix_images_imagehash'), 'images', ['imagehash'], unique=False)
    op.create_index(op.f('ix_images_job_id'), 'images', ['job_id'], unique=False)
    op.create_index(op.f('ix_images_name'), 'images', ['name'], unique=False)
    op.create_index(op.f('ix_images_order'), 'images', ['order'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_images_order'), table_name='images')
    op.drop_index(op.f('ix_images_name'), table_name='images')
    op.drop_index(op.f('ix_images_job_id'), table_name='images')
    op.drop_index(op.f('ix_images_imagehash'), table_name='images')
    op.drop_index(op.f('ix_images_image_uploaded'), table_name='images')
    op.drop_index(op.f('ix_images_created_date'), table_name='images')
    op.drop_index(op.f('ix_images_alto_uploaded'), table_name='images')
    op.drop_table('images')
    op.drop_index(op.f('ix_jobs_worker_key_id'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_state'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_started_date'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_proarc_json_uploaded'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_proarc_json_required'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_owner_key_id'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_last_change'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_finished_date'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_created_date'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_alto_required'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_keys_role'), table_name='keys')
    op.drop_index(op.f('ix_keys_last_used'), table_name='keys')
    op.drop_index(op.f('ix_keys_label'), table_name='keys')
    op.drop_index(op.f('ix_keys_key_hash'), table_name='keys')
    op.drop_index(op.f('ix_keys_created_date'), table_name='keys')
    op.drop_index(op.f('ix_keys_active'), table_name='keys')
    op.drop_table('keys')
    # ### end Alembic commands ###
